# Issues and Resolutions

* Q: urllib3.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
* Connecting to self signed cert deployed server.

See [here](issues/q1/source.py)